export const FETCH_RECORD_REQUEST = 'LAST_REC_REQUEST'
export const FETCH_RECORD_SUCCESS = 'LAST_REC_SUCCESS'
export const FETCH_RECORD_FAIL = 'LAST_REC_FAIL'

export const FIELD_DATA_REQUEST = 'FIELD_DATA_REQUEST'
export const FIELD_DATA_SUCCESS = 'FIELD_DATA_SUCCESS'
export const FIELD_DATA_FAIL = 'FIELD_DATA_FAIL'